services:
  # proxies requests to internal services
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on:
      - solar_module
      - frontend
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # vue frontend
  frontend:
    image: frontend
    container_name: frontend
    build: 
      context: ./frontend
    depends_on:
      - solar_module
    ports: 
      - 8080:80

  # provides measurement data
  solar_module:
    image: solar_module
    container_name: solar_module
    build: 
      context: ./solar_module
    ports:
      - 5001:5001