services:
  # vue frontend
  frontend:
    image: frontend
    container_name: frontend
    build: 
      context: ./frontend
    depends_on:
      - solar_module
      - web_socket
    ports: 
      - 8080:80

  # web socket
  web_socket:
    image: web_socket
    container_name: web_socket
    build:
      context: ./web_socket
    depends_on:
      - solar_module
    ports:
      - 4000:4000

  # provides measurement data
  solar_module:
    image: solar_module
    container_name: solar_module
    build: 
      context: ./solar_module
    ports:
      - 5001:5001
    volumes:
      - ~/solarpanel_data:/data
    privileged: true